name: "Add a New Project"
description: Submit projects, services, or apps that are part of the Arweave ecosystem.
title: "[NEW]: "
labels: []
assignees: ['afisher3578']

body:

- type: markdown
  attributes:
  value: | ## Quick Checklist  
   Thank you for submitting a new Permaweb project. Please ensure:

      - The project is active
      - It uses Arweave or AO for core functionality

- type: input
  id: project-name
  attributes:
  label: Project Name
  validations:
  required: true

- type: input
  id: meta-description
  attributes:
  label: Meta Description
  placeholder: Short one-line summary of the project.
  validations:
  required: true

- type: textarea
  id: project-overview
  attributes:
  label: Overview
  placeholder: Briefly describe the project and its purpose.
  validations:
  required: true

- type: input
  id: official-website
  attributes:
  label: Official Website
  placeholder: "https://example.com"
  validations:
  required: true

- type: dropdown
  id: project-categories
  attributes:
  label: Project Categories
  description: Select one or more categories. The first selection is considered the primary category.
  multiple: true
  options: - Labs - Infrastructure - Bridge - Investment - Wallet - Community - DeFi - AI - Block Explorer - Developer Tools - Gaming - Creator Economy - NFT
  validations:
  required: true

- type: input
  id: x-handle
  attributes:
  label: X Handle
  placeholder: "@example"
  validations:
  required: false

- type: input
  id: discord-invite
  attributes:
  label: Discord Invite Link
  placeholder: "https://discord.com/invite/example"
  validations:
  required: false

- type: input
  id: github-repo
  attributes:
  label: GitHub Repository
  placeholder: "https://github.com/example"
  validations:
  required: false

- type: input
  id: telegram-link
  attributes:
  label: Telegram link
  validations:
  required: false

- type: input
  id: additional-link-1
  attributes:
  label: Additional link 1
  validations:
  required: false

- type: input
  id: additional-link-2
  attributes:
  label: Additional link 2
  validations:
  required: false

- type: input
  id: additional-link-3
  attributes:
  label: Additional link 3
  validations:
  required: false

- type: checkboxes
  id: project-affiliation
  attributes:
  label: Are you affiliated with this project?
  options: - label: I am affiliated with this project
  required: false


